### ISSUE TITLE
[BUG] confrest.py unit test does not work with PyT 1.10.0

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#304]
### Bug description
I am using  `nvcr.io/nvstaging/merlin/tmp-merlin-pytorch-training:nightly`  image which has PyT 1.10.0 version. I upgraded the transformers version to 4.12.2 as well to make the code work with  PyT 1.10.0 version.

I get the following error when running [confest.py](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/tests/conftest.py) unit test. Most likely the error occurs because HF library cannot import  Tensor object from the base torch so it fails as it imports it from T4Rec torch api instead.

```
root@b0fb60cbba22:/workspace/Transformers4Rec/tests# pytest conftest.py
ImportError while loading conftest '/workspace/Transformers4Rec/tests/conftest.py'.
conftest.py:61: in <module>
    from tests.torch.conftest import *  # noqa
torch/conftest.py:21: in <module>
    tr = pytest.importorskip("transformers4rec.torch")
../transformers4rec/torch/__init__.py:21: in <module>
    from ..config.transformer import (
../transformers4rec/config/transformer.py:76: in <module>
    class ReformerConfig(T4RecConfig, transformers.ReformerConfig):
/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py:2140: in __getattr__
    module = self._get_module(self._class_to_module[name])
/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py:2152: in _get_module
    raise RuntimeError(
E   RuntimeError: Failed to import transformers.models.reformer because of the following error (look up to see its traceback):
E   Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
E   cannot import name 'Tensor' from 'torch' (/workspace/Transformers4Rec/tests/torch/__init__.py)
```

if I run the unit test as below the error does not pop up because the path of Torch is correct:

```
root@b0fb60cbba22:/workspace/Transformers4Rec# pytest ./tests/conftest.py
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /workspace/Transformers4Rec
plugins: pythonpath-0.7.3, cov-3.0.0, hypothesis-4.50.8
collected 0 items                                                                                                                                                                              

==================================================================================== no tests ran in 0.01s =====================================================================================
```

### Expected behavior

All unit tests should work without errors.

### Environment details
- Transformers4Rec version:  v.0.1.1
- Platform: Docker
- Python version: 3.8.12
- Huggingface Transformers version:4.12.2
- PyTorch version (GPU?): 1.10.0
- Tensorflow version (GPU?): NA
